[package]
name = "history"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-rocksdb = "0.44"
tokio = { version = "*", features = ["full"] }
bitcoincore-rpc = "0.19"
log = "*"
serde = "*"
serde_json = "*"
dirs = "6.0"