[package]
name = "indexer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "*", features = ["full"] }
bitcoincore-rpc = "0.19"
ord = "0.23"
ordinals = "*"
lru = "*" 
serde_json = "*" 
log = "*"
reqwest = "*"